name: Terraform Plan (Dev)

on:
  push:
    branches: [dev]
    paths:
      - "projects/learning/environments/dev/**"
      - "projects/learning2/environments/dev/**"

jobs:
  plan-learning:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: projects/learning/environments/dev

  plan-learning2:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: projects/learning2/environments/dev
