name: Terraform Plan (Prod)

on:
  push:
    branches: [main]
    paths:
      - "projects/learning/environments/prod/**"
      - "projects/learning2/environments/prod/**"

jobs:
  plan-learning:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: projects/learning/environments/prod

  plan-learning2:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: projects/learning2/environments/prod
