name: Terraform Dev

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Setup GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64_DEV }}" | base64 -d > /tmp/account.json

      - name: Override tfvars for GitHub Actions
        run: |
          echo 'credentials_file = ""' > environments/dev/terraform.override.tfvars

      - name: Terraform Init
        working-directory: environments/dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: terraform init

      - name: Terraform Format Check
        working-directory: environments/dev
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: environments/dev
        run: terraform validate

      - name: Terraform Plan or Apply
        working-directory: environments/dev
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            terraform plan -var-file="terraform.override.tfvars"
          else
            terraform apply -auto-approve -var-file="terraform.override.tfvars"
          fi
