name: Terraform Plan for Production

on:
  pull_request:
    branches:
      - prod
      - main

jobs:
  terraform-plan:
    name: Terraform Plan Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.3

      - name: Setup GCP Credentials
        run: |
          echo "${{ secrets.GCP_SA_KEY_B64 }}" | base64 -d > /tmp/account.json
        shell: bash

      - name: Override tfvars for GitHub Actions
        run: |
          echo 'credentials_file = ""' > environments/prod/terraform.override.tfvars

      - name: Terraform Init
        working-directory: environments/prod
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: terraform init

      - name: Terraform Format Check
        working-directory: environments/prod
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        working-directory: environments/prod
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/prod
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: terraform plan -var-file="terraform.override.tfvars"
