name: Terraform Plan (Dev)

on:
  push:
    branches: [dev]
    paths:
      - "environments/dev/**"

jobs:
  call-plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      environment: dev
