name: Terraform Plan (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-creds.json

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Decode GCP Service Account
        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > "$GOOGLE_APPLICATION_CREDENTIALS"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Terraform Init
        working-directory: environments/${{ inputs.environment }}
        run: terraform init

      - name: Terraform Format
        working-directory: environments/${{ inputs.environment }}
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: environments/${{ inputs.environment }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/${{ inputs.environment }}
        run: terraform plan
