name: Terraform Plan

on:
  pull_request:
    branches: [main]

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect Changed Environments
        id: changes
        run: |
          changed_dirs=$(git diff --name-only origin/main...HEAD \
            | grep -E '^projects/[^/]+/environments/(dev|prod)/' \
            | cut -d '/' -f1-4 \
            | sort -u)

          echo "changed=${changed_dirs}" >> $GITHUB_OUTPUT

      - name: Exit if No Matching Env
        if: steps.changes.outputs.changed == ''
        run: echo "No dev/prod environment changes detected. Skipping."

      - name: Decode GCP SA
        if: steps.changes.outputs.changed != ''
        run: echo "${{ secrets.GCP_SA_KEY_BASE64 }}" | base64 -d > gcp-creds.json

      - name: Set up Terraform
        if: steps.changes.outputs.changed != ''
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.11.4

      - name: Terraform Init & Plan (per env)
        if: steps.changes.outputs.changed != ''
        run: |
          for env_dir in ${{ steps.changes.outputs.changed }}; do
            echo "==> Planning in $env_dir"
            terraform -chdir=$env_dir init
            terraform -chdir=$env_dir fmt -check
            terraform -chdir=$env_dir validate
            terraform -chdir=$env_dir plan
          done
